### ISSUE TITLE
Making a new logo

### ISSUE THREAD

**Issue by bbusagroningen** [ttencate/rugscriptie#2]
Could you please let me know how could I create a new logo, due to the fact that the "faculty of mathematics and natural sciences" department has been renamed to "science and engineering". Also would it be possible to add another small text. Something like you see in the attached image. 
![screen shot 2018-04-17 at 13 19 31](https://user-images.githubusercontent.com/21987084/38868281-ca751e98-4246-11e8-884d-046ebd9a6192.jpg)

**Comment by ttencate** [comment]
I had some spare time today so I added the Faculty of Science and Engineering logo.

As for adding extra stuff, that's not yet supported and would take a bit more effort. Pull requests are welcome :)

**Comment by bbusagroningen** [comment]
Great, thank you! 
Would you mind sharing the source code for the logos though?

**Comment by ttencate** [comment]
I don't have any source code. These logos come straight from https://www.rug.nl/about-us/how-to-find-us/huisstijl/logobank/logobestandenfaculteiten/. All I did was an EPS → PDF conversion using `epstopdf`.
