### ISSUE TITLE
Errors in producing correct output

### ISSUE THREAD

**Issue by thepredathor** [ttencate/rugscriptie#3]
Hello,

I think the whole repo misses two files: the georgia.afm and georgia.tfm.

Besides the logo, everything else does not appear in the representation due to the lack of those two files.

rugscriptie.sty shows an error: Font \georgia=georgia not loadable: Metric (TFM) fine not found.

Program used: Overleaf

**Comment by ttencate** [comment]
It's possible that the necessary files were installed elsewhere on my system so I didn't notice the problem.

Could you try the procedure at https://stackoverflow.com/a/6306477/14637 to generate the missing files, see if it helps, and submit a pull request? (Rather than putting the files in the texmf tree, I hope it suffices to just leave them in the current directory.)

**Comment by thepredathor** [comment]
While using the overleaf program, i put the files from an older version of the template and i put the files in the archive, in the same directory and it did not work. Right now, I am sorry but I can't do any tadk of what you asked me as I am new to latex and I am running on a really tight schedule

**Comment by ttencate** [comment]
OK, I had a closer look at this. It seems you downloaded the source files (i.e. this repo) rather than the built output ZIP linked to in the README. That ZIP file does contain the .afm and .tfm files.

Going to close this now; let me know if you still have trouble!

**Comment by thepredathor** [comment]
Sorry for bothering again, but in the zip file from the read me there are no FSE logos or the option to choose fse in the page. They are only in the repo, but not in the zip file from the read me

**Comment by ttencate** [comment]
You are right, seems I might have uploaded an old ZIP file instead of the actual v1.1.0 version. Should be better now!

**Comment by thepredathor** [comment]
Thank you very much!
